vim.o.expandtab = false
vim.o.smartindent = true
vim.o.tabstop = 4
vim.o.softtabstop = 4
vim.o.shiftwidth = 4
vim.wo.relativenumber = true
vim.wo.number = true
vim.opt.numberwidth = 4
vim.g.mapleader = " "
vim.o.wrap = false
vim.opt.colorcolumn = "80,100"
